(()=>{'use strict';
const SUPABASE_URL='https://woxdfibdpbsxqhmvmjoz.supabase.co';
const SUPABASE_KEY='sb_publishable_hXBUybGAWLK1FbkK3HIHXA_7cH7vG0m';
const STORE='financialFreedomPlannerV6';
const wait=fn=>window.supabase?fn(window.supabase):setTimeout(()=>wait(fn),150);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function loadXLSX(){if(window.XLSX)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx-js-style@1.2.0/dist/xlsx.bundle.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
function collectState(){const read=id=>document.getElementById(id);const payouts=[...document.querySelectorAll('#payoutList input[type="number"]')].map((el,i)=>({label:`Payout ${i+1}`,amount:Math.max(0,Number(el.value)||0)}));const active=document.querySelector('input[name="rule"]:checked');const custom={needs:Number(read('customNeeds')?.value)||0,wants:Number(read('customWants')?.value)||0,savings:Number(read('customSavings')?.value)||0};const items={needs:[],wants:[],savings:[]};document.querySelectorAll('.expense-group').forEach((group,i)=>{const k=['needs','wants','savings'][i];group.querySelectorAll('.expense-row').forEach(row=>{const fields=row.querySelectorAll('input');items[k].push({name:fields[0]?.value||'Untitled',amount:Math.max(0,Number(fields[1]?.value)||0)})})});return{payoutType:read('payoutType')?.value||'biweekly',payouts:payouts.length?payouts:[{label:'Payout 1',amount:0}],rule:active?.value||'503020',custom,items}}
function localSave(state){try{localStorage.setItem(STORE,JSON.stringify(state))}catch(_){} }
function money(v){return new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(Math.round(Number(v)||0))}
function init(api){
 const $=id=>document.getElementById(id);
 const authBtn=$('authBtn'),saveBtn=$('saveBudget'),downloadBtn=$('downloadBudget'),modal=$('authModal'),form=$('authForm'),close=$('authClose'),sw=$('authSwitch');
 if(!authBtn||!modal||!form||!saveBtn||!downloadBtn)return;
 const saveState=$('saveState'), title=$('authTitle'), copy=$('authCopy'), submit=$('authSubmit'), msg=$('authMessage'), email=$('authEmail'), pass=$('authPassword');
 const replace=el=>{const n=el.cloneNode(true);el.replaceWith(n);return n};
 const btn=replace(authBtn),save=replace(saveBtn),download=replace(downloadBtn),authForm=replace(form),authClose=replace(close),authSwitch=replace(sw);
 let session=null,mode='login',busy=false;
 const setStatus=(a,b,kind='')=>{saveState.className='save-state '+kind;saveState.innerHTML=`<strong>${a}</strong><span>${b}</span>`};
 const apply=()=>{const logged=!!session;save.hidden=!logged;btn.textContent=logged?'Log out':'Log in';if(logged){setStatus('Unsaved changes','Click Save budget to store this version.');title.textContent='Account';copy.textContent=`Signed in as ${session.email}`;authSwitch.hidden=true;submit.textContent='Close';msg.textContent=session.email}else{setStatus('Local draft','Sign in to save your budget to the cloud.');title.textContent=mode==='signup'?'Create your account':'Log in';copy.textContent=mode==='signup'?'Create an account to save your budgets across devices.':'Sign in to save and restore your budget across devices.';authSwitch.hidden=false;submit.textContent=mode==='signup'?'Sign up':'Log in';authSwitch.textContent=mode==='signup'?'Already have an account? Log in':'Need an account? Sign up';msg.textContent=''}};
 const open=()=>{modal.hidden=false;msg.textContent='';setTimeout(()=>email.focus(),0)};
 async function rest(path,opts={}){const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),10000);try{const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...opts,signal:ctrl.signal,headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json',...(opts.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch(_){}if(!r.ok)throw new Error(data?.message||data?.hint||data?.error||`Request failed (${r.status})`);return data}finally{clearTimeout(timer)}}
 async function loadCloudOnce(){if(!session||sessionStorage.getItem('ffCloudHydrated')==='1')return;try{const rows=await rest(`budgets?select=id,name,data,updated_at&user_id=eq.${encodeURIComponent(session.id)}&order=updated_at.desc&limit=1`,{method:'GET'});if(rows?.[0]?.data){localSave(rows[0].data);sessionStorage.setItem('ffCloudHydrated','1');location.reload();return true} }catch(err){setStatus('Signed in','Could not load your saved budget.','unsaved');msg.textContent=err.message}return false}
 btn.addEventListener('click',async()=>{if(busy)return;if(session){busy=true;const old=session;try{await api.auth.signOut();session=null;sessionStorage.removeItem('ffCloudHydrated');apply()}catch(err){msg.textContent=err.message}finally{busy=false}return}mode='login';apply();open()});
 authClose.addEventListener('click',()=>modal.hidden=true);modal.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true});authSwitch.addEventListener('click',()=>{mode=mode==='login'?'signup':'login';apply()});
 authForm.addEventListener('submit',async ev=>{ev.preventDefault();if(busy)return;if(session){modal.hidden=true;return}busy=true;submit.disabled=true;msg.textContent='';try{const em=email.value.trim(),pw=pass.value;const r=mode==='login'?await api.auth.signInWithPassword({email:em,password:pw}):await api.auth.signUp({email:em,password:pw,options:{emailRedirectTo:location.origin+location.pathname}});if(r.error)throw new Error(r.error.message);if(mode==='signup'&&!r.data.session){msg.textContent='Account created. Check your email to confirm, then log in.';return}session=r.data.session?.user?{...r.data.session.user,access_token:r.data.session.access_token}:null;modal.hidden=true;apply();if(session)await loadCloudOnce()}catch(err){msg.textContent=err.message}finally{busy=false;submit.disabled=false}});
 save.addEventListener('click',async()=>{if(!session){open();msg.textContent='Please log in to save your budget.';return}const state=collectState();save.disabled=true;save.textContent='Saving…';try{const rows=await rest(`budgets?select=id&user_id=eq.${encodeURIComponent(session.id)}&order=updated_at.desc&limit=1`,{method:'GET'});const payload=JSON.stringify({user_id:session.id,name:'My Budget',data:state,updated_at:new Date().toISOString()});if(rows?.[0]?.id){await rest(`budgets?id=eq.${encodeURIComponent(rows[0].id)}&user_id=eq.${encodeURIComponent(session.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:payload})}else{await rest('budgets',{method:'POST',headers:{Prefer:'return=minimal'},body:payload})}localSave(state);sessionStorage.setItem('ffCloudHydrated','1');setStatus('Saved','Saved to your account.','saved')}catch(err){setStatus('Save failed',err.message||'Please try again.','unsaved')}finally{save.disabled=false;save.textContent='Save budget'}});
 download.addEventListener('click',async()=>{try{const state=collectState();await loadXLSX();const income=state.payouts.reduce((s,p)=>s+(Number(p.amount)||0),0);const rs={503020:{name:'50 / 30 / 20',needs:50,wants:30,savings:20},702010:{name:'70 / 20 / 10',needs:70,wants:10,savings:20},6040:{name:'60 / 40',spending:60,savings:40},8020:{name:'80 / 20',spending:80,savings:20}};const r=state.rule==='custom'?{name:'Custom',needs:+state.custom.needs||0,wants:+state.custom.wants||0,savings:+state.custom.savings||0}:rs[state.rule]||rs[503020];const target=k=>r.spending?(k==='savings'?income*r.savings/100:income*r.spending/100):income*r[k]/100;const planned=k=>state.items[k].reduce((s,x)=>s+(Number(x.amount)||0),0);const rows=[['FINANCIAL FREEDOM BUDGET'],['Monthly plan'],['Take-home pay',income],['Payout schedule',state.payoutType],['Budgeting rule',r.name],[],['BUDGET TARGETS','Target','Planned','Status'],['Needs',target('needs'),planned('needs'),planned('needs')<=target('needs')?'Within target':'Over target'],['Wants',target('wants'),planned('wants'),planned('wants')<=target('wants')?'Within target':'Over target'],['Savings / Debt',target('savings'),planned('savings'),planned('savings')<=target('savings')?'Within target':'Over target'],[],['PAYOUTS','Amount'],...state.payouts.map(p=>[p.label,Number(p.amount)||0]),['Total take-home',income],[],['EXPENSES','Item','Planned amount','Share of take-home'],...Object.entries(state.items).flatMap(([k,a])=>a.map(x=>[k==='needs'?'Needs':k==='wants'?'Wants':'Savings / Debt',x.name,Number(x.amount)||0,income?(Number(x.amount)||0)/income:0]))];const wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:24},{wch:30},{wch:20},{wch:24}];ws['!freeze']={xSplit:0,ySplit:1};const styleRange=(range,s)=>{const ref=XLSX.utils.decode_range(range);for(let R=ref.s.r;R<=ref.e.r;R++)for(let C=ref.s.c;C<=ref.e.c;C++){const a=XLSX.utils.encode_cell({r:R,c:C});ws[a]=ws[a]||{t:'s',v:''};ws[a].s=Object.assign({},ws[a].s||{},s)}};const navy='16233B',blue='2563EB',white='FFFFFF';styleRange('A1:D1',{fill:{fgColor:{rgb:navy}},font:{bold:true,color:{rgb:white},sz:18}});styleRange('A7:D7',{fill:{fgColor:{rgb:blue}},font:{bold:true,color:{rgb:white}}});const payoutHeader=12,expenseHeader=14+state.payouts.length;styleRange(`A${payoutHeader}:B${payoutHeader}`,{fill:{fgColor:{rgb:blue}},font:{bold:true,color:{rgb:white}}});styleRange(`A${expenseHeader}:D${expenseHeader}`,{fill:{fgColor:{rgb:blue}},font:{bold:true,color:{rgb:white}}});Object.keys(ws).forEach(k=>{if(k[0]==='!')return;const c=ws[k];if(c&&typeof c.v==='number')c.z=k.startsWith('D')?'0.0%':'₱#,##0'});XLSX.utils.book_append_sheet(wb,ws,'Monthly Budget');XLSX.writeFile(wb,'financial-freedom-budget.xlsx')}catch(err){alert('Excel export failed: '+err.message)}});
 api.auth.onAuthStateChange((_event,s)=>{session=s?.user?{...s.user,access_token:s.access_token}:null;apply()});api.auth.getSession().then(({data})=>{session=data.session?.user?{...data.session.user,access_token:data.session.access_token}:null;apply();if(session)loadCloudOnce()});
 apply();
}
wait(supabase=>init(supabase.createClient(SUPABASE_URL,SUPABASE_KEY)));
})();