(()=>{'use strict';
const SUPABASE_URL='https://woxdfibdpbsxqhmvmjoz.supabase.co';
const SUPABASE_KEY='sb_publishable_hXBUybGAWLK1FbkK3HIHXA_7cH7vG0m';
const STORE='financialFreedomPlannerV6';
const wait=fn=>window.supabase?fn(window.supabase):setTimeout(()=>wait(fn),150);
async function loadXLSX(){if(window.XLSX)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx-js-style@1.2.0/dist/xlsx.bundle.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
function init(api){
 const $=id=>document.getElementById(id);const getState=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch(_){return null}};
 const authBtn=$('authBtn'),saveBtn=$('saveBudget'),downloadBtn=$('downloadBudget'),modal=$('authModal'),form=$('authForm'),close=$('authClose'),sw=$('authSwitch'),title=$('authTitle'),copy=$('authCopy'),submit=$('authSubmit'),msg=$('authMessage'),email=$('authEmail'),pass=$('authPassword'),saveState=$('saveState');
 if(!authBtn||!modal||!form||!saveBtn||!downloadBtn)return;
 let session=null,mode='login',busy=false;
 // Replace event-bearing controls so the older auth/save/export handlers cannot fire twice.
 const replace=(el)=>{const n=el.cloneNode(true);el.replaceWith(n);return n};
 const btn=replace(authBtn), save=replace(saveBtn), download=replace(downloadBtn), authForm=replace(form), authClose=replace(close), authSwitch=replace(sw);
 const authEmail=$('authEmail'), authPassword=$('authPassword'), authSubmit=$('authSubmit'), authMessage=$('authMessage'), authTitle=$('authTitle'), authCopy=$('authCopy');
 function setStatus(text,detail,kind){saveState.className='save-state '+(kind||'');saveState.innerHTML=`<strong>${text}</strong><span>${detail}</span>`}
 function paint(){const logged=!!session;save.hidden=!logged;btn.textContent=logged?'Log out':'Log in';if(logged){setStatus('Ready to save','Click Save budget to save this version to your account.','');authTitle.textContent='Account';authCopy.textContent=`Signed in as ${session.user.email}`;authSwitch.hidden=true;authSubmit.textContent='Close';}else{setStatus('Local draft','Sign in to save your budget to the cloud.','');authTitle.textContent=mode==='signup'?'Create your account':'Log in';authCopy.textContent=mode==='signup'?'Create an account to save your budgets across devices.':'Sign in to save and restore your budget across devices.';authSwitch.hidden=false;authSubmit.textContent=mode==='signup'?'Sign up':'Log in';authSwitch.textContent=mode==='signup'?'Already have an account? Log in':'Need an account? Sign up';}}
 function openAuth(){modal.hidden=false;authMessage.textContent='';if(!session){authPassword.value='';setTimeout(()=>authEmail.focus(),0)}}
 async function loadCloud(){if(!session)return;const {data,error}=await api.from('budgets').select('id,name,data,updated_at').eq('user_id',session.user.id).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(error){setStatus('Signed in','Could not load your saved budget.','unsaved');return}if(data?.data){localStorage.setItem(STORE,JSON.stringify(data.data));setStatus('Budget restored','Your latest saved budget was loaded.','saved');setTimeout(()=>location.reload(),60)}else{setStatus('Ready to save','No saved budget yet.','')}}
 btn.addEventListener('click',async()=>{if(busy)return;if(session){busy=true;const {error}=await api.auth.signOut();busy=false;if(error){authMessage.textContent=error.message;return}session=null;paint();return}mode='login';paint();openAuth()});
 authClose.addEventListener('click',()=>modal.hidden=true);
 modal.addEventListener('click',e=>{if(e.target===modal)modal.hidden=true});
 authSwitch.addEventListener('click',()=>{mode=mode==='login'?'signup':'login';paint()});
 authForm.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;if(session){modal.hidden=true;return}busy=true;authSubmit.disabled=true;authMessage.textContent='';const em=authEmail.value.trim(),pw=authPassword.value;const r=mode==='login'?await api.auth.signInWithPassword({email:em,password:pw}):await api.auth.signUp({email:em,password:pw,options:{emailRedirectTo:location.origin+location.pathname}});busy=false;authSubmit.disabled=false;if(r.error){authMessage.textContent=r.error.message;return}if(mode==='signup'&&!r.data.session){authMessage.textContent='Account created. Check your email, then sign in.';return}session=r.data.session;modal.hidden=true;paint();await loadCloud()});
 save.addEventListener('click',async()=>{if(!session){openAuth();authMessage.textContent='Please log in to save your budget.';return}const state=getState();if(!state){setStatus('Nothing to save','Build your budget first.','unsaved');return}save.disabled=true;save.textContent='Saving…';let error=null;if(window.__ffBudgetId){({error}=await api.from('budgets').update({data:state,updated_at:new Date().toISOString()}).eq('id',window.__ffBudgetId).eq('user_id',session.user.id));}else{const r=await api.from('budgets').select('id').eq('user_id',session.user.id).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(r.data?.id){window.__ffBudgetId=r.data.id;({error}=await api.from('budgets').update({data:state,updated_at:new Date().toISOString()}).eq('id',window.__ffBudgetId).eq('user_id',session.user.id));}else{const ins=await api.from('budgets').insert({user_id:session.user.id,name:'My Budget',data:state}).select('id').single();error=ins.error;window.__ffBudgetId=ins.data?.id||null}}save.disabled=false;save.textContent='Save budget';if(error){setStatus('Save failed',error.message||'Please try again.','unsaved')}else{setStatus('Saved','Saved to your account.','saved')}});
 download.addEventListener('click',async()=>{try{const state=getState();if(!state){alert('There is no budget to export yet.');return}await loadXLSX();const money=v=>Number(v)||0;const income=state.payouts.reduce((s,p)=>s+money(p.amount),0);const rules={503020:{name:'50 / 30 / 20',needs:50,wants:30,savings:20},702010:{name:'70 / 20 / 10',needs:70,wants:10,savings:20},6040:{name:'60 / 40',spending:60,savings:40},8020:{name:'80 / 20',spending:80,savings:20}};const r=state.rule==='custom'?{name:'Custom',needs:+state.custom.needs||0,wants:+state.custom.wants||0,savings:+state.custom.savings||0}:rules[state.rule]||rules[503020];const target=(k)=>r.spending?(k==='savings'?income*r.savings/100:income*r.spending/100):income*r[k]/100;const rows=[['FINANCIAL FREEDOM BUDGET'],['Monthly plan'],['Take-home pay',income],['Payout schedule',state.payoutType],['Budgeting rule',r.name],[],['BUDGET TARGETS','Target','Planned','Status'],['Needs',target('needs'),state.items.needs.reduce((s,x)=>s+money(x.amount),0),''],['Wants',target('wants'),state.items.wants.reduce((s,x)=>s+money(x.amount),0),''],['Savings / Debt',target('savings'),state.items.savings.reduce((s,x)=>s+money(x.amount),0),''],[],['PAYOUTS','Amount'],...state.payouts.map(p=>[p.label,money(p.amount)]),['Total take-home',income],[],['EXPENSES','Item','Planned amount','Share of take-home'],...Object.entries(state.items).flatMap(([k,a])=>a.map(x=>[k==='needs'?'Needs':k==='wants'?'Wants':'Savings / Debt',x.name,money(x.amount),income?money(x.amount)/income:0]))];const wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:24},{wch:30},{wch:20},{wch:24}];ws['!freeze']={xSplit:0,ySplit:1};const style=(range,s)=>{const ref=XLSX.utils.decode_range(range);for(let R=ref.s.r;R<=ref.e.r;R++)for(let C=ref.s.c;C<=ref.e.c;C++){const a=XLSX.utils.encode_cell({r:R,c:C});ws[a]=ws[a]||{t:'s',v:''};ws[a].s=Object.assign({},ws[a].s||{},s)}};const navy='16233B',blue='2563EB',white='FFFFFF',line='D8E0EC';style('A1:D1',{fill:{fgColor:{rgb:navy}},font:{bold:true,color:{rgb:white},sz:18}});style('A7:D7',{fill:{fgColor:{rgb:blue}},font:{bold:true,color:{rgb:white}}});style('A12:B12',{fill:{fgColor:{rgb:blue}},font:{bold:true,color:{rgb:white}}});style(`A${12+state.payouts.length+3}:D${12+state.payouts.length+3}`,{fill:{fgColor:{rgb:blue}},font:{bold:true,color:{rgb:white}}});Object.keys(ws).forEach(k=>{if(k[0]==='!')return;const c=ws[k];if(c&&typeof c.v==='number'){if(k.startsWith('D'))c.z='0.0%';else c.z='₱#,##0'}});XLSX.utils.book_append_sheet(wb,ws,'Monthly Budget');XLSX.writeFile(wb,'financial-freedom-budget.xlsx')}catch(err){alert('Excel export failed. Please try again.')}});
 // Use the currently authenticated session without reloading the page; only cloud restore reloads once.
 api.auth.onAuthStateChange((event,s)=>{session=s?.user? s:null;paint();if(event==='SIGNED_IN'&&session)loadCloud();});
 api.auth.getSession().then(({data})=>{session=data.session?.user?data.session:null;paint();if(session)loadCloud()});
 paint();
}
wait(supabase=>init(supabase.createClient(SUPABASE_URL,SUPABASE_KEY)));
})();