(()=>{'use strict';
const sb=window.__ffSupabase||window.supabase.createClient('https://woxdfibdpbsxqhmvmjoz.supabase.co','sb_publishable_hXBUybGAWLK1FbkK3HIHXA_7cH7vG0m');
const $=id=>document.getElementById(id),money=v=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(Math.round(Number(v)||0));
const defaults={needs:[['Housing',0],['Groceries',0]],wants:[['Dining out',0],['Subscriptions',0]],savings:[['Emergency fund',0],['Debt payment',0]]};
const rules={503020:{label:'50 / 30 / 20',desc:'50% needs, 30% wants, 20% savings or debt.',needs:50,wants:30,savings:20},702010:{label:'70 / 20 / 10',desc:'70% needs, 10% wants, 20% savings or debt.',needs:70,wants:10,savings:20},6040:{label:'60 / 40',desc:'60% spending, 40% savings or debt.',spending:60,savings:40},8020:{label:'80 / 20',desc:'80% spending, 20% savings or debt.',spending:80,savings:20},custom:{label:'Custom',desc:'Set your own targets.'}};
let session=null,budgetId=null,busy=false;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function normalize(d){d=d||{};const items={};for(const g of ['needs','wants','savings']){const src=Array.isArray(d.items?.[g])&&d.items[g].length?d.items[g]:defaults[g];items[g]=src.map((x,i)=>Array.isArray(x)?[String(x[0]||'Untitled'),Number(x[1])||0]:[String(x?.name||`Item ${i+1}`),Number(x?.amount)||0])}return{frequency:['weekly','biweekly','monthly'].includes(d.frequency||d.payoutType)?(d.frequency||d.payoutType):'biweekly',payouts:(Array.isArray(d.payouts)&&d.payouts.length?d.payouts:[{amount:0},{amount:0}]).map((p,i)=>({label:String(p?.label||`Payout ${i+1}`),amount:Number(p?.amount)||0})),rule:rules[d.rule]?d.rule:'503020',custom:{needs:Number(d.custom?.needs)||50,wants:Number(d.custom?.wants)||30,savings:Number(d.custom?.savings)||20},items}}
function read(){const items={needs:[],wants:[],savings:[]};document.querySelectorAll('#expenseGrid .expense-group').forEach((g,i)=>{const key=['needs','wants','savings'][i];g.querySelectorAll('.expense-row').forEach(r=>{const x=r.querySelectorAll('input');items[key].push([x[0]?.value?.trim()||'Untitled',Math.max(0,Number(x[1]?.value)||0)])})});return{frequency:$('frequency')?.value||'biweekly',payouts:[...document.querySelectorAll('#payouts .payout-row')].map((r,i)=>({label:`Payout ${i+1}`,amount:Math.max(0,Number(r.querySelector('input')?.value)||0)})),rule:document.querySelector('input[name="rule"]:checked')?.value||'503020',custom:{needs:Number($('needsPct')?.value)||0,wants:Number($('wantsPct')?.value)||0,savings:Number($('savingsPct')?.value)||0},items}}
function totals(s){return Object.fromEntries(['needs','wants','savings'].map(g=>[g,s.items[g].reduce((a,x)=>a+Number(x[1]||0),0)]))}
function targets(s,income){const r=rules[s.rule];if(s.rule==='custom')return{needs:income*s.custom.needs/100,wants:income*s.custom.wants/100,savings:income*s.custom.savings/100,spending:income*(s.custom.needs+s.custom.wants)/100};if(r.spending)return{needs:null,wants:null,savings:income*r.savings/100,spending:income*r.spending/100};return{needs:income*r.needs/100,wants:income*r.wants/100,savings:income*r.savings/100,spending:null}}
function dirty(){const st=$('saveState');if(st){st.textContent='Unsaved changes';st.className='state'}if($('save'))$('save').disabled=false}
function render(s){$('frequency').value=s.frequency;$('needsPct').value=s.custom.needs;$('wantsPct').value=s.custom.wants;$('savingsPct').value=s.custom.savings;$('customWrap').hidden=s.rule!=='custom';
const rl=$('ruleList');rl.innerHTML='';Object.entries(rules).forEach(([k,r])=>{const l=document.createElement('label');l.className='rule'+(k===s.rule?' active':'');l.innerHTML=`<span class="rule-top"><input type="radio" name="rule" value="${k}" ${k===s.rule?'checked':''}><span>${r.label}</span></span><span class="desc">${r.desc}</span>`;l.querySelector('input').onchange=()=>{s.rule=k;render(s);dirty()};rl.append(l)});
const p=$('payouts');p.innerHTML='';s.payouts.forEach((x,i)=>{const r=document.createElement('div');r.className='payout-row';r.innerHTML=`<input type="number" min="0" step="1" value="${x.amount}" aria-label="Payout ${i+1}"><button class="remove" type="button" ${s.payouts.length===1?'disabled':''}>×</button>`;r.querySelector('input').oninput=dirty;r.querySelector('.remove').onclick=()=>{s.payouts.splice(i,1);render(s);dirty()};p.append(r)});
const eg=$('expenseGrid');eg.innerHTML='';[['needs','Needs'],['wants','Wants'],['savings','Savings / Debt']].forEach(([k,t])=>{const g=document.createElement('div');g.className='expense-group';g.innerHTML=`<div class="group-head"><strong>${t}</strong><span class="total"></span></div><div class="note group-note"></div><div class="expense-items"></div><button class="btn secondary add-item" type="button">+ Add item</button>`;const list=g.querySelector('.expense-items');s.items[k].forEach((x,i)=>{const r=document.createElement('div');r.className='expense-row';r.innerHTML=`<input type="text" value="${esc(x[0])}"><input type="number" min="0" step="1" value="${x[1]}"><button class="remove" type="button">×</button>`;r.querySelectorAll('input').forEach(n=>n.oninput=dirty);r.querySelector('.remove').onclick=()=>{s.items[k].splice(i,1);render(s);dirty()};list.append(r)});g.querySelector('.add-item').onclick=()=>{s.items[k].push(['New item',0]);render(s);dirty()};eg.append(g)});derived(s);$('saveState').textContent='Unsaved changes';$('saveState').className='state'}
function derived(s){const income=s.payouts.reduce((a,p)=>a+Number(p.amount||0),0),t=totals(s),tar=targets(s,income),planned=t.needs+t.wants+t.savings,r=rules[s.rule];$('incomeDisplay').textContent=money(income);$('incomeMeta').textContent=income?`${s.payouts.length} payout ${s.payouts.length===1?'entry':'entries'} • ${s.frequency==='biweekly'?'bi-weekly':s.frequency}`:'Add your payouts to start planning.';$('ruleSummary').textContent=`${r.label} • ${r.desc}`;const pct=income?Math.round(planned/income*100):0;$('bar').style.width=Math.min(100,pct)+'%';$('percent').textContent=pct+'%';const st=$('status'),de=$('detail');if(!income){st.textContent='Add income';st.className='warn';de.textContent='Enter your take-home pay first.'}else if(planned<=income){st.textContent='Within income';st.className='good';de.textContent=`${money(income-planned)} unallocated`}else{st.textContent='Over planned';st.className='bad';de.textContent=`${money(planned-income)} over take-home`}
const cards=s.rule==='6040'||s.rule==='8020'?[['Spending',t.needs+t.wants,tar.spending],['Savings / debt',t.savings,tar.savings],['Unassigned',Math.max(0,income-planned),null]]:[['Needs',t.needs,tar.needs],['Wants',t.wants,tar.wants],['Savings / debt',t.savings,tar.savings]];$('budgetGrid').innerHTML=cards.map(c=>`<div class="budget-card"><strong>${c[0]}</strong><div class="budget-number">${money(c[1])}</div><div class="note">${c[2]==null?'Track actual amount':`Target ${money(c[2])}`}</div></div>`).join('');document.querySelectorAll('#expenseGrid .expense-group').forEach((g,i)=>{const k=['needs','wants','savings'][i],actual=t[k],target=tar[k]??tar.spending,delta=target-actual;g.querySelector('.total').textContent=money(actual);g.querySelector('.group-note').textContent=target==null?'Part of total spending':delta>=0?`${money(delta)} remaining`:`${money(-delta)} over target`;g.querySelector('.group-note').className='note group-note '+(target==null?'':delta>=0?'good':'bad')})}
async function load(){const r=await sb.from('budgets').select('id,data,updated_at').eq('user_id',session.user.id).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(r.error)throw r.error;if(r.data){budgetId=r.data.id;render(normalize(r.data.data));$('saveState').textContent='Saved to your account';$('saveState').className='state saved'}else render(normalize(null))}
async function save(){if(busy)return;const s=read();if(s.rule==='custom'&&s.custom.needs+s.custom.wants+s.custom.savings!==100){$('message').textContent='Custom percentages must add up to 100%.';return}busy=true;$('save').disabled=true;$('message').textContent='Saving…';try{const payload={frequency:s.frequency,payoutType:s.frequency,payouts:s.payouts,rule:s.rule,custom:s.custom,items:s.items};let r=budgetId?await sb.from('budgets').update({name:'My Budget',data:payload,updated_at:new Date().toISOString()}).eq('id',budgetId).eq('user_id',session.user.id):await sb.from('budgets').insert({user_id:session.user.id,name:'My Budget',data:payload}).select('id').single();if(r.error)throw r.error;if(r.data?.id)budgetId=r.data.id;$('saveState').textContent='Saved to your account';$('saveState').className='state saved';$('message').textContent='Budget saved to your account.'}catch(e){$('message').textContent=e.message||'Could not save your budget.';dirty()}finally{busy=false;$('save').disabled=false}}
function exportExcel(){const s=read(),income=s.payouts.reduce((a,p)=>a+p.amount,0),t=totals(s),tar=targets(s,income),rows=[['Financial Freedom Budget'],['Frequency',s.frequency],['Monthly take-home',income],['Rule',rules[s.rule].label],[],['Category','Item','Amount'],...['needs','wants','savings'].flatMap(k=>s.items[k].map(x=>[k==='needs'?'Needs':k==='wants'?'Wants':'Savings / debt',x[0],x[1]])),[],['Summary','Actual','Target'],['Needs',t.needs,tar.needs??tar.spending],['Wants',t.wants,tar.wants??tar.spending],['Savings / debt',t.savings,tar.savings],['Total planned',t.needs+t.wants+t.savings,income]];const done=()=>{const ws=XLSX.utils.aoa_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Budget');XLSX.writeFile(wb,'financial-freedom-budget.xlsx');$('message').textContent='Excel budget downloaded.'};if(window.XLSX)done();else{const sc=document.createElement('script');sc.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';sc.onload=done;sc.onerror=()=>{$('message').textContent='Excel export could not be loaded.'};document.head.append(sc)}}
function patch(){for(const id of ['save','excel','reset','addPayout','logout']){const old=$(id);if(!old)continue;const b=old.cloneNode(true);old.replaceWith(b);if(id==='save')b.onclick=save;if(id==='excel')b.onclick=exportExcel;if(id==='addPayout')b.onclick=()=>{const s=read();s.payouts.push({amount:0});render(s);dirty()};if(id==='reset')b.onclick=()=>{if(confirm('Start a new budget draft? Your saved budget will remain unchanged until you click Save budget.'))render(normalize(null))};if(id==='logout')b.onclick=async()=>{const r=await sb.auth.signOut();if(!r.error)location.replace('./index.html')}}}
sb.auth.getSession().then(async({data,error})=>{if(error||!data.session){location.replace('./index.html');return}session=data.session;if($('userEmail'))$('userEmail').textContent=session.user.email||'';patch();try{await load();const q=new URLSearchParams(location.search);if(q.get('return')==='rules')setTimeout(()=>document.querySelector('.rules-section')?.scrollIntoView({behavior:'smooth'}),150)}catch(e){$('message').textContent=e.message||'Could not load your saved budget.';render(normalize(null))}});sb.auth.onAuthStateChange((_event,next)=>{if(!next)location.replace('./index.html')});
})();